// <auto-generated />
namespace ControlardorDePedidos.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cadastrodeclientes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cadastrodeclientes));
        
        string IMigrationMetadata.Id
        {
            get { return "201707132031299_cadastro-de-clientes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
